# GitHub Pages Configuration
title: BetterSlip - AI-Native Betting Copilot
description: Official documentation and blog for BetterSlip - Your AI-powered sports betting platform
url: https://dannybszn.github.io
baseurl: /BetterSlip-
theme: null

# SEO and metadata
author: BetterSlip Team
twitter:
  username: betterslip_
  card: summary_large_image
logo: /assets/logo.png

# Google Analytics (add your ID when ready)
# google_analytics: G-XXXXXXXXXX

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - fetch-blog-content.js
  - convert-old-blogs.js
  - .gitignore
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "BetterSlip Team"